//User Variables
const MIN_PASSWORD_LENGTH = 6;
const PASSWORD_SALT_LENGTH = 8;

//Hotel Variables
const FILE_SIZE_LIMIT = 5 * 1024 * 1024;
const NUMBER_FILES_LIMIT = 6;
const MIN_STAR_RATING = 1;
const MAX_STAR_RATING = 5;

export {
  MIN_PASSWORD_LENGTH,
  PASSWORD_SALT_LENGTH,
  FILE_SIZE_LIMIT,
  NUMBER_FILES_LIMIT,
  MIN_STAR_RATING,
  MAX_STAR_RATING,
};
